version: "3.7"


services:
  nginx:
    build:
      context: "."
    image: nginx:latest
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<name>.rule=Host(`<name>.docker.localhost`)"
    volumes:
      - "../path/to/public:/usr/share/nginx/html:ro"

